import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Strips basic markdown for TXT export
 */
const stripMarkdown = (markdown) => {
    return markdown
        .replace(/\*\*(.*?)\*\*/g, '$1') // Bold
        .replace(/\*(.*?)\*/g, '$1') // Italic
        .replace(/#(.*?)\n/g, '$1\n') // Headers
        .replace(/\[(.*?)\]\(.*?\)/g, '$1') // Links
        .replace(/!\[.*?\]\(.*?\)/g, '') // Images
        .replace(/`{3}[\s\S]*?`{3}/g, '[Code Block Removed]') // Code blocks
        .replace(/`(.*?)`/g, '$1') // Inline code
        .trim();
};

/**
 * Downloads raw text or markdown
 */
const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
};

/**
 * Recursively removes unsupported CSS functions and separates components for multi-page PDF
 */
const sanitizeElementForPDF = (element) => {
    // 1. Create a deep clone so we do NOT modify the actual live UI
    const clone = element.cloneNode(true);
    const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

    // 2. Create the Premium Header (Gold & Black) - Standardized for every page
    const header = document.createElement('div');
    header.style.cssText = `
        background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
        color: #ffffff;
        padding: 30px 40px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: 4px solid #facc15; 
        width: 800px;
        box-sizing: border-box;
    `;
    header.innerHTML = `
        <div style="display: flex; flex-direction: column;">
            <span style="font-size: 24px; font-weight: 900; letter-spacing: 2px; color: #facc15;">LIYA AI</span>
            <span style="font-size: 9px; text-transform: uppercase; letter-spacing: 2px; color: #94a3b8; font-weight: 700;">Research & Intelligence Division</span>
        </div>
        <div style="background: rgba(250, 204, 21, 0.1); border: 1px solid #facc15; padding: 4px 10px; border-radius: 4px;">
            <span style="color: #facc15; font-size: 9px; font-weight: 800;">CONFIDENTIAL REPORT</span>
        </div>
    `;

    // 3. Create a clean BODY container for the actual answer
    const body = document.createElement('div');
    body.style.cssText = `
        padding: 40px 60px;
        line-height: 1.6;
        font-size: 14px;
        background-color: #f8fafc;
        width: 800px;
        box-sizing: border-box;
    `;
    body.appendChild(clone);

    // 4. Create the Template Footer (Dynamic Part will be added by jsPDF)
    const footer = document.createElement('div');
    footer.style.cssText = `
        padding: 20px 60px;
        border-top: 1px solid #e2e8f0;
        background: #ffffff;
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 9px;
        color: #64748b;
        width: 800px;
        box-sizing: border-box;
    `;
    footer.innerHTML = `
        <div>Generated by <strong>LIYA</strong> for <strong>Navraj</strong></div>
        <div>${timestamp} | Kolkata</div>
    `;

    // 5. Build an invisible container for the components
    const offScreenContainer = document.createElement('div');
    offScreenContainer.style.position = 'absolute';
    offScreenContainer.style.left = '-9999px';
    offScreenContainer.style.top = '-9999px';
    offScreenContainer.appendChild(header);
    offScreenContainer.appendChild(body);
    offScreenContainer.appendChild(footer);
    document.body.appendChild(offScreenContainer);

    // 6. Force specific styles on the cloned content
    const replaceUnsupportedColors = (node) => {
        if (node.nodeType === 1) { // ELEMENT_NODE
            const computedStyle = window.getComputedStyle(node);
            
            const isUnsupported = (val) => val && (val.includes('oklch') || val.includes('oklab'));
            
            // Aggressively force safe colors on the inline style to override CSS
            // This is key: html2canvas prioritizes inline styles over computed styles from CSS
            if (isUnsupported(computedStyle.color)) {
                node.style.setProperty('color', '#0f172a', 'important');
            }
            
            if (isUnsupported(computedStyle.backgroundColor)) {
                node.style.setProperty('background-color', 'transparent', 'important');
            }
            
            if (isUnsupported(computedStyle.borderColor)) {
                node.style.setProperty('border-color', '#e2e8f0', 'important');
            }

            if (isUnsupported(computedStyle.fill)) {
                node.style.setProperty('fill', 'currentColor', 'important');
            }

            if (isUnsupported(computedStyle.stroke)) {
                node.style.setProperty('stroke', 'currentColor', 'important');
            }

            // Special handling for code blocks
            if (node.tagName === 'PRE' || node.tagName === 'CODE') {
                node.style.setProperty('background-color', '#1e293b', 'important');
                node.style.setProperty('color', '#e2e8f0', 'important');
                node.style.padding = '15px';
                node.style.borderRadius = '6px';
            }
            
            // Headers
            if (['H1', 'H2', 'H3', 'H4', 'H5', 'H6'].includes(node.tagName)) {
                node.style.setProperty('color', '#1e293b', 'important');
                node.style.borderLeft = '4px solid #facc15';
                node.style.paddingLeft = '10px';
                node.style.marginTop = '20px';
            }
        }
        for (let i = 0; i < node.childNodes.length; i++) {
            replaceUnsupportedColors(node.childNodes[i]);
        }
    };

    replaceUnsupportedColors(clone);

    return { 
        header, 
        body, 
        footer, 
        wrapper: offScreenContainer 
    };
};

/**
 * Converts a React Markdown ref to a beautiful Multi-Page PDF
 */
const downloadPDF = async (elementRef, filename) => {
    if (!elementRef.current) return false;

    let config = null;

    try {
        config = sanitizeElementForPDF(elementRef.current);
        
        // 1. Generate Canvases for components
        const headerCanvas = await html2canvas(config.header, { scale: 2, backgroundColor: '#1e293b' });
        const footerCanvas = await html2canvas(config.footer, { scale: 2, backgroundColor: '#ffffff' });
        const bodyCanvas = await html2canvas(config.body, { scale: 2, useCORS: true, backgroundColor: '#f8fafc' });

        // Cleanup
        document.body.removeChild(config.wrapper);

        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = pdf.internal.pageSize.getHeight();

        const imgWidth = pdfWidth;
        const headerHeight = (headerCanvas.height * imgWidth) / headerCanvas.width;
        const footerHeight = (footerCanvas.height * imgWidth) / footerCanvas.width;
        const bodyImgHeight = (bodyCanvas.height * imgWidth) / bodyCanvas.width;

        // Content Area Height per page
        const pageBodyLimit = pdfHeight - headerHeight - footerHeight - 10; // 10mm margin
        const totalPages = Math.ceil(bodyImgHeight / pageBodyLimit);

        for (let i = 0; i < totalPages; i++) {
            if (i > 0) pdf.addPage();

            // A. ADD REPEATING HEADER
            const headerData = headerCanvas.toDataURL('image/png');
            pdf.addImage(headerData, 'PNG', 0, 0, imgWidth, headerHeight);

            // B. ADD BODY SLICE
            const bodyData = bodyCanvas.toDataURL('image/png');
            pdf.addImage(
                bodyData, 
                'PNG', 
                0, 
                headerHeight + 5, 
                imgWidth, 
                pageBodyLimit, 
                undefined, 
                'FAST',
                0
            );

            // C. ADD REPEATING FOOTER
            const footerData = footerCanvas.toDataURL('image/png');
            pdf.addImage(footerData, 'PNG', 0, pdfHeight - footerHeight, imgWidth, footerHeight);
            
            // D. ADD PAGE NUMBER
            pdf.setFontSize(8);
            pdf.setTextColor(150);
            pdf.text(`Page ${i + 1} of ${totalPages}`, pdfWidth - 30, pdfHeight - 10);
        }

        pdf.save(filename);
        return true;
    } catch (error) {
        console.error("Multi-Page PDF Generation failed:", error);
        if (config && config.wrapper && document.body.contains(config.wrapper)) {
            document.body.removeChild(config.wrapper);
        }
        return false;
    }
};

/**
 * Main Export Router
 */
export const exportReport = async (content, format, elementRef = null) => {
    const defaultName = `Liya_Report_${new Date().getTime()}`;

    let cleanContent = content
        .replace(/\[SYSTEM NOTIFICATION:.*?\]/g, '')
        .replace(/\(Task Output: /g, '')
        .replace(/\)$/g, '')
        .trim();

    switch (format) {
        case 'MD':
            downloadFile(cleanContent, `${defaultName}.md`, 'text/markdown');
            break;
        case 'TXT':
            downloadFile(stripMarkdown(cleanContent), `${defaultName}.txt`, 'text/plain');
            break;
        case 'PDF':
            if (elementRef && elementRef.current) {
                await downloadPDF(elementRef, `${defaultName}.pdf`);
            } else {
                downloadFile(stripMarkdown(cleanContent), `${defaultName}.txt`, 'text/plain');
            }
            break;
        default:
            downloadFile(stripMarkdown(cleanContent), `${defaultName}.txt`, 'text/plain');
    }
};
